import AVFoundation
import Foundation

/// Plays Velora's synthesized UI sounds (design brief §5): rising = listening,
/// falling = done, low = error. Assets are generated by scripts/make-sounds.sh
/// into Resources/ and bundled into the .app.
final class SoundPlayer {
    enum Cue: String {
        case start, stop, error
    }

    private var players: [Cue: AVAudioPlayer] = [:]

    init() {
        for cue in [Cue.start, .stop, .error] {
            guard let url = ResourceLocator.resource(named: cue.rawValue, extension: "caf") else {
                NSLog("Velora: missing sound asset %@.caf (run scripts/make-sounds.sh)", cue.rawValue)
                continue
            }
            do {
                let player = try AVAudioPlayer(contentsOf: url)
                player.prepareToPlay()
                players[cue] = player
            } catch {
                NSLog("Velora: failed to load %@.caf: %@", cue.rawValue, "\(error)")
            }
        }
    }

    /// Plays a cue if sounds are enabled; volume from the settings slider.
    func play(_ cue: Cue) {
        let config = AppConfig.shared
        guard config.soundsEnabled, let player = players[cue] else { return }
        player.volume = Float(config.soundVolume / 100.0)
        player.currentTime = 0
        player.play()
    }
}
